[tool.poetry]
name = "NormCap"
version = "0.1.0"
description = "Intelligent screencapture tool to capture information instead of images "
license = "MIT"
authors = ["Dynobo <dynobo@mailbox.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
mss = "^4.0"
pillow = "^6.1"
pyocr = "^0.7.2"
pyperclip = "^1.7"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pytest-cov = "^2.4"
black = "==19.3b0"
flake8 = "*"
isort = "*"
mypy = "*"
pre-commit = "*"
pyinstaller = "^3.5"
vprof = "^0.37.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

