[tool.poetry]
name = "NormCap"
version = "0.1.0"
description = "Intelligent screencapture tool to capture information instead of images "
license = "MIT"
authors = ["Dynobo <dynobo@mailbox.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
PyAutoGUI = "^0.9.47"
pathlib2 = "^2.3"
mss = "^4.0"
pillow = "^6.1"
pygame = "^1.9"
wxPython = "^4.0"
PyUserInput = "^0.1.11"
pynput = "^1.4"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pytest-cov = "^2.4"
black = "==19.3b0"
flake8 = "*"
isort = "*"
mypy = "*"
pre-commit = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

