name: Linux x64 - lint, test & build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master    
    
    # PREPARE
    - name: Install Python 3.7 
      # Because GitHub Actions' python isn't build against tkinter!
      run: sudo apt-get update && sudo apt-get install python3.7 python3.7-dev python3-pip python3.7-tk python3-pil.imagetk
    - name: Install normcap dependencies
      run: sudo apt-get install tesseract-ocr libtesseract-dev libleptonica-dev pkg-config xclip
    - name: Install pipenv
      run: python3.7 -m pip install --user pipenv
    - name: Create virtual env
      run: $HOME/.local/bin/pipenv install --dev
    
    # LINT
    - name: Lint with flake8
      run: $HOME/.local/bin/pipenv run flake8 . --count --show-source --statistics

    # TEST
    - name: Test with pytest
      # xvfb-run with bpp 32 has to be used to make the mss screenshot grab work
      run: $HOME/.local/bin/pipenv run xvfb-run --server-args="-screen 0 1024x768x24+32" python3.7 -m pytest  
    
    # BUILD
    - name: Build executable
      run:  $HOME/.local/bin/pipenv run python3.7 build.py      
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: $GITHUB_REF-normcap
        path: dist/normcap