name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master    
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7           
    - name: Install system dependencies
      run: > 
        sudo apt-get install 
        tesseract-ocr libtesseract-dev libleptonica-dev 
        pkg-config xclip python3-tk python3-pil.imagetk tk8.6 tk8.6-dev tk tk-dev
    - name: Install pipenv
      run: |
        sudo pip3 install pipenv
        dpkg -s python3-tk
        python -v
    - name: Install python dependencies
      run: | 
        pipenv --bare install --dev
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. 
        pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
    - name: Test with pytest
      run: |
        pipenv run pytest
