name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master    
    # - name: Set up Python 3.7
    #   uses: actions/setup-python@v1
    #   with:
    #     python-version: '3.7'
    #     architecture: 'x64' 
    - name: Install system dependencies
      run: > 
        sudo apt-get update &&
        sudo apt-get install 
        tesseract-ocr libtesseract-dev libleptonica-dev 
        pkg-config xclip
        python3-all python3-pip
        python3.7-tk python3-pil python3.7
        tk tk-dev tcl
    - name: Install pipenv
      run: |
        python3.7 -m pip install --upgrade pip
        python3.7 -m pip install pipenv
    - name: Install python dependencies
      run: | 
        pipenv --bare install --dev
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. 
        pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
    - name: Test tkinter import
      run: |
        printf 'import tkinter\ntkinter._test()\n' > test.py
        pipenv run python test.py      
        pipenv run python -m normcap
    - name: Test with pytest
      run: |
        pipenv run python -m pytest
